"""Add tables relationships

Revision ID: 26244eefa17b
Revises: ae543fc2fe81
Create Date: 2020-09-05 01:04:31.561022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26244eefa17b'
down_revision = 'ae543fc2fe81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduling')
    # ### end Alembic commands ###
