"""update relationships v2.9.1

Revision ID: 347188c2aeb6
Revises: abc0ef9e9072
Create Date: 2020-09-10 02:07:53.581417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347188c2aeb6'
down_revision = 'abc0ef9e9072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
