"""update relationships v2.4

Revision ID: 5ae44313eb84
Revises: b0790aea4475
Create Date: 2020-09-09 21:43:49.287362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae44313eb84'
down_revision = 'b0790aea4475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_scheduling_mtm',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduling_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheduling_id'], ['schedulings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scheduling_id')
    )
    op.drop_constraint('users_lesson_date_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'lesson_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lesson_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_lesson_date_fkey', 'users', 'schedulings', ['lesson_date'], ['id'])
    op.drop_table('users_scheduling_mtm')
    # ### end Alembic commands ###
