"""Add tables relationships v1.4

Revision ID: 7ee126cf5700
Revises: c0b0421f1c4e
Create Date: 2020-09-05 12:16:39.377771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ee126cf5700'
down_revision = 'c0b0421f1c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduling')
    op.add_column('students', sa.Column('lesson_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'schedulings', ['lesson_time_id'], ['id'])
    op.add_column('subjects', sa.Column('lesson_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'schedulings', ['lesson_time_id'], ['id'])
    op.add_column('teachers', sa.Column('lesson_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'schedulings', ['lesson_time_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'lesson_time_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'lesson_time_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'lesson_time_id')
    op.create_table('scheduling',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scheduling_pkey')
    )
    op.drop_table('schedulings')
    # ### end Alembic commands ###
