"""update relationships v1.0

Revision ID: 8846b920257f
Revises: 012052a5effd
Create Date: 2020-09-06 22:58:46.570864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8846b920257f'
down_revision = '012052a5effd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subjects', sa.Column('lesson_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'schedulings', ['lesson_time_id'], ['id'])
    op.add_column('users', sa.Column('lesson_date', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'schedulings', ['lesson_date'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'lesson_date')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'lesson_time_id')
    op.drop_table('schedulings')
    # ### end Alembic commands ###
