"""update relationships v2.6

Revision ID: abc0ef9e9072
Revises: 5ae44313eb84
Create Date: 2020-09-09 23:40:44.131520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc0ef9e9072'
down_revision = '5ae44313eb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulings', sa.Column('confirmation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedulings', 'confirmation')
    # ### end Alembic commands ###
