"""update relationships v2.0

Revision ID: b0790aea4475
Revises: 8846b920257f
Create Date: 2020-09-06 23:11:03.556003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0790aea4475'
down_revision = '8846b920257f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_users_roles',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], )
    )
    op.drop_table('association_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_users',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='association_users_student_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='association_users_teacher_id_fkey')
    )
    op.drop_table('association_users_roles')
    # ### end Alembic commands ###
