"""test for heroku

Revision ID: b3c0482c54cc
Revises: f8d560b4efa9
Create Date: 2020-09-14 21:56:30.873983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c0482c54cc'
down_revision = 'f8d560b4efa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'test')
    # ### end Alembic commands ###
