"""update relationships v2.9.3

Revision ID: c6c360cee356
Revises: 347188c2aeb6
Create Date: 2020-09-10 02:25:03.167817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c360cee356'
down_revision = '347188c2aeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    # ### end Alembic commands ###
