"""update relationships v2.9.4

Revision ID: c83dfe127856
Revises: c6c360cee356
Create Date: 2020-09-12 21:52:09.662720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83dfe127856'
down_revision = 'c6c360cee356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulings', sa.Column('subject', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedulings', 'subjects', ['subject'], ['id'])
    op.drop_constraint('subjects_lesson_time_id_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'lesson_time_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('lesson_time_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_lesson_time_id_fkey', 'subjects', 'schedulings', ['lesson_time_id'], ['id'])
    op.drop_constraint(None, 'schedulings', type_='foreignkey')
    op.drop_column('schedulings', 'subject')
    # ### end Alembic commands ###
