"""update relationships v2.9.6

Revision ID: f8d560b4efa9
Revises: 8047f3d4c47a
Create Date: 2020-09-12 22:24:39.718219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d560b4efa9'
down_revision = '8047f3d4c47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulings', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.drop_constraint('schedulings_subject_fkey', 'schedulings', type_='foreignkey')
    op.create_foreign_key(None, 'schedulings', 'subjects', ['subject_id'], ['id'])
    op.drop_column('schedulings', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulings', sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedulings', type_='foreignkey')
    op.create_foreign_key('schedulings_subject_fkey', 'schedulings', 'subjects', ['subject'], ['id'])
    op.drop_column('schedulings', 'subject_id')
    # ### end Alembic commands ###
